Update prompt and organize alias

diff --git a/zsh/zsh-prompt b/zsh/zsh-prompt
--- a/zsh/zsh-prompt
+++ b/zsh/zsh-prompt
@@ -1,51 +1,48 @@
-# #!/bin/sh
-
-# ## autoload vcs and colors
-# autoload -Uz vcs_info
-# autoload -U colors && colors
-
-# # enable only git 
-# zstyle ':vcs_info:*' enable git 
-
-# # setup a hook that runs before every ptompt. 
-# precmd_vcs_info() { vcs_info }
-# precmd_functions+=( precmd_vcs_info )
-# setopt prompt_subst
-
-# # add a function to check for untracked files in the directory.
-# # from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
-# # zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
-# # 
-# # +vi-git-untracked(){
-# #     # if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
-# #     #     git status --porcelain | grep '??' &> /dev/null ; then
-# #     #     # This will show the marker if there are any untracked files in repo.
-# #     #     # If instead you want to show the marker only if there are untracked
-# #     #     # files in $PWD, use:
-# #     #     #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
-# #     #     hook_com[staged]+='!' # signify new files with a bang
-# #     # fi
-# # }
-
-# # zstyle ':vcs_info:*' check-for-changes true
-# # zstyle ':vcs_info:git:*' formats " %r/%S %b %m%u%c "
-# zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[magenta]%} %b%{$fg[blue]%})"
-
-# # format our main prompt for hostname current folder, and permissions.
-# # PROMPT="%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[red]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}"
-# PROMPT="%B%{$fg[gray]%}%{$fg[gray]%}%n%{$fg[gray]%}@%{$fg[gray]%}%M%{$fg[gray]%} %{$fg[cyan]%}%c%{$reset_color%}"
-# # PROMPT="%{$fg[green]%}%n@%m %~ %{$reset_color%}%#> "
-# PROMPT+="\$vcs_info_msg_0_ "
-# # TODO look into this for more colors
-# # https://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/
-# # also ascii escape codes
-
-# Customize prompt
 autoload -Uz vcs_info
-precmd() { vcs_info }
+autoload -Uz add-zsh-hook
 
-zstyle ':vcs_info:git:*' formats '%b ' #%b is the branch name
+# Function to update VCS info asynchronously
+update_vcs_info() {
+    vcs_info
+    zle && zle .reset-prompt
+}
 
+# Register the precmd hook
+add-zsh-hook precmd update_vcs_info
+
+# Customize the VCS information
+zstyle ':vcs_info:git:*' formats '%F{yellow}%b%f%F{red}%c%f%F{green}%u%f '
+zstyle ':vcs_info:git:*' actionformats '%F{yellow}%b|%a%f '
+
+# Command execution time
+TIMER=0
+preexec() {
+    TIMER=$SECONDS
+}
+precmd() {
+    if [[ $TIMER -gt 0 ]]; then
+        ELAPSED_TIME=$(($SECONDS - $TIMER))
+        TIMER_FORMAT="%F{cyan}[$ELAPSED_TIME sec]%f "
+    else
+        TIMER_FORMAT=''
+    fi
+}
+
+# Return status of the last executed command
+return_status() {
+    if [ $? -eq 0 ]; then
+        echo "%F{green}✔%f"
+    else
+        echo "%F{red}✖%f"
+    fi
+}
+
+# Shorten directory path
+prompt_dir() {
+    echo "%F{cyan}%3~%f"
+}
+
+# Final Prompt
 setopt PROMPT_SUBST
-NEWLINE=$'\n'
-PROMPT='%F{green}%*%f %F{cyan}%~%f %F{red}${vcs_info_msg_0_}${NEWLINE}%f$ '
+PROMPT='%F{magenta}%n@%m%f %B%F{blue}%T%f%b $(prompt_dir) $(return_status) ${vcs_info_msg_0_} ${TIMER_FORMAT}
+%# '
